name: bina
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - folium
  - scipy
  - requests
  - plotly
  - pyproj
  - openpyxl
  - pip
